import numpy as np
from numpy.typing import NDArray

def version() -> str: ...

# cards
def parse_card(text: str) -> int: ...
def card_to_str(card: int) -> str: ...

# evaluator
def evaluate(cards: list[int]) -> int: ...
def evaluate_batch(cards: NDArray[np.uint8]) -> NDArray[np.uint32]: ...
def hand_category(value: int) -> int: ...

# isomorphism
class HandIndexer:
    def __init__(self, cards_per_round: list[int]) -> None: ...
    @property
    def size(self) -> int: ...
    @property
    def total_cards(self) -> int: ...
    @property
    def cards_per_round(self) -> list[int]: ...
    def index(self, cards: list[int]) -> int: ...
    def unindex(self, index: int) -> list[int]: ...
    def index_batch(self, cards: NDArray[np.uint8]) -> NDArray[np.uint64]: ...
    def unindex_batch(self, indices: NDArray[np.uint64]) -> NDArray[np.uint8]: ...
