import numpy as np
from numpy.typing import NDArray

def version() -> str: ...

# cards
def parse_card(text: str) -> int: ...
def card_to_str(card: int) -> str: ...

# evaluator
def evaluate(cards: list[int]) -> int: ...
def evaluate_batch(cards: NDArray[np.uint8]) -> NDArray[np.uint32]: ...
def hand_category(value: int) -> int: ...

# isomorphism
class HandIndexer:
    def __init__(self, cards_per_round: list[int]) -> None: ...
    @property
    def size(self) -> int: ...
    @property
    def total_cards(self) -> int: ...
    @property
    def cards_per_round(self) -> list[int]: ...
    def index(self, cards: list[int]) -> int: ...
    def unindex(self, index: int) -> list[int]: ...
    def index_batch(self, cards: NDArray[np.uint8]) -> NDArray[np.uint64]: ...
    def unindex_batch(self, indices: NDArray[np.uint64]) -> NDArray[np.uint8]: ...

# engine
class Street:
    PREFLOP: Street
    FLOP: Street
    TURN: Street
    RIVER: Street
    def __int__(self) -> int: ...
    @property
    def value(self) -> int: ...

class PlayerStatus:
    ACTIVE: PlayerStatus
    FOLDED: PlayerStatus
    ALL_IN: PlayerStatus
    def __int__(self) -> int: ...

class ActionType:
    FOLD: ActionType
    CHECK_CALL: ActionType
    BET_RAISE: ActionType

class Action:
    def __init__(self, type: ActionType, amount: int = 0) -> None: ...
    @property
    def type(self) -> ActionType: ...
    @property
    def amount(self) -> int: ...
    @staticmethod
    def fold() -> Action: ...
    @staticmethod
    def check_call() -> Action: ...
    @staticmethod
    def bet_raise_to(amount: int) -> Action: ...

class LegalActions:
    @property
    def fold(self) -> bool: ...
    @property
    def check_call(self) -> bool: ...
    @property
    def call_amount(self) -> int: ...
    @property
    def bet_raise(self) -> bool: ...
    @property
    def min_raise_to(self) -> int: ...
    @property
    def max_raise_to(self) -> int: ...

class Pot:
    @property
    def amount(self) -> int: ...
    @property
    def eligible(self) -> list[int]: ...

class HandState:
    def __init__(
        self,
        starting_stacks: list[int],
        small_blind: int,
        big_blind: int,
        record_history: bool = True,
    ) -> None: ...
    @property
    def num_players(self) -> int: ...
    @property
    def button(self) -> int: ...
    @property
    def street(self) -> Street: ...
    @property
    def is_terminal(self) -> bool: ...
    @property
    def is_showdown(self) -> bool: ...
    @property
    def to_act(self) -> int: ...
    @property
    def current_bet(self) -> int: ...
    @property
    def pot(self) -> int: ...
    @property
    def non_folded(self) -> int: ...
    @property
    def stacks(self) -> list[int]: ...
    @property
    def bets(self) -> list[int]: ...
    @property
    def contributed(self) -> list[int]: ...
    @property
    def statuses(self) -> list[PlayerStatus]: ...
    @property
    def history(self) -> list[tuple[Street, int, Action]]: ...
    def legal_actions(self) -> LegalActions: ...
    def why_illegal(self, action: Action) -> str | None: ...
    def apply(self, action: Action) -> None: ...
    def pots(self) -> list[Pot]: ...
    def payoffs(self, hole_cards: list[list[int]], board: list[int]) -> list[int]: ...
    def copy(self) -> HandState: ...

# cfr
class NashConvResult:
    @property
    def best_response(self) -> list[float]: ...
    @property
    def on_policy(self) -> list[float]: ...
    @property
    def nash_conv(self) -> float: ...

class CfrSolver:
    def __init__(
        self,
        game: str,
        seed: int = 0,
        threads: int = 1,
        lcfr_until: int = 0,
        discount_interval: int = 1000,
        prune_after: int = -1,
        prune_probability: float = 0.95,
        prune_threshold: float = -1e9,
        regret_floor: float = -1e30,
        max_infosets: int = 1048576,
    ) -> None: ...
    def run(self, max_iterations: int, max_seconds: float = 1e18) -> int: ...
    @property
    def iteration(self) -> int: ...
    @property
    def num_infosets(self) -> int: ...
    @property
    def memory_bytes(self) -> int: ...
    @property
    def num_players(self) -> int: ...
    def nash_conv(self) -> NashConvResult: ...
    def average_strategy(self) -> list[tuple[int, list[float]]]: ...
    def strategy(self, key: int) -> list[float]: ...
    def export_strategy(
        self,
    ) -> tuple[NDArray[np.uint64], NDArray[np.uint32], NDArray[np.float32]]: ...
    def save(self) -> bytes: ...
    def load(self, data: bytes) -> None: ...

# card abstraction
def hole_index(a: int, b: int) -> int: ...
def river_equities(board: list[int]) -> NDArray[np.float32]: ...
def river_ochs(board: list[int], cluster_of: NDArray[np.uint8], k: int) -> NDArray[np.float32]: ...
def river_ochs_one(
    hole: list[int], board: list[int], cluster_of: NDArray[np.uint8], k: int
) -> NDArray[np.float32]: ...
def turn_histograms(board: list[int], bins: int) -> NDArray[np.uint8]: ...
def turn_histogram_one(hole: list[int], board: list[int], bins: int) -> NDArray[np.uint8]: ...
def preflop_class_of_hole() -> NDArray[np.uint8]: ...
def preflop_class_equity(samples: int, seed: int, threads: int) -> list[float]: ...
def sample_river_ochs(
    boards: int, seed: int, cluster_of: NDArray[np.uint8], k: int, threads: int
) -> NDArray[np.float32]: ...
def sample_turn_histograms(
    boards: int, seed: int, bins: int, threads: int
) -> NDArray[np.uint8]: ...
def flop_features(
    turn_table: NDArray[np.uint16], turn_rank: NDArray[np.uint16], threads: int
) -> tuple[NDArray[np.uint8], NDArray[np.float32]]: ...
def build_river_table(
    cluster_of: NDArray[np.uint8], k: int, centroids: NDArray[np.float32], threads: int
) -> NDArray[np.uint16]: ...
def build_turn_table(
    bins: int, centroids: NDArray[np.float32], threads: int
) -> NDArray[np.uint16]: ...
def build_flop_table(
    turn_table: NDArray[np.uint16],
    turn_rank: NDArray[np.uint16],
    centroids: NDArray[np.float32],
    threads: int,
) -> NDArray[np.uint16]: ...

# action abstraction
class PreflopSizing:
    open_bb: list[float]
    reraise_x_ip: list[float]
    reraise_x_oop: list[float]
    four_bet_x: list[float]
    all_in: bool
    max_raises: int
    def __init__(self) -> None: ...

class PostflopSizing:
    bet_pot: list[float]
    raise_pot: list[float]
    all_in: bool
    max_raises: int
    def __init__(self) -> None: ...

class ActionRules:
    chips_per_bb: int
    preflop: PreflopSizing
    postflop: list[tuple[int, PostflopSizing]]
    def __init__(self) -> None: ...

def abstract_actions(state: HandState, rules: ActionRules) -> list[Action]: ...
def pot_fraction(state: HandState, to: int) -> float: ...
def pseudo_harmonic(a: float, b: float, x: float) -> float: ...
def translate(state: HandState, rules: ActionRules, action: Action) -> list[tuple[int, float]]: ...
def translate_bet(
    state: HandState, rules: ActionRules, pot_fraction: float, all_in: bool
) -> list[tuple[int, float]]: ...
def equity_vs_range(
    hole: list[int],
    board: list[int],
    weights: NDArray[np.float32],
    samples: int = 1000,
    seed: int = 0,
) -> float: ...

# hold'em training
def NlheSolver(
    starting_stacks: list[int],
    small_blind: int,
    big_blind: int,
    rules: ActionRules,
    flop_table: NDArray[np.uint16],
    turn_table: NDArray[np.uint16],
    river_table: NDArray[np.uint16],
    seed: int = 0,
    threads: int = 1,
    lcfr_until: int = 0,
    discount_interval: int = 1000,
    prune_after: int = -1,
    prune_probability: float = 0.95,
    prune_threshold: float = -1e9,
    regret_floor: float = -1e30,
    max_infosets: int = 1048576,
) -> CfrSolver: ...
def nlhe_history_root() -> int: ...
def nlhe_extend_history(history: int, action_index: int) -> int: ...
def nlhe_infoset_key(history: int, bucket: int) -> int: ...
