import numpy as np
from numpy.typing import NDArray

def version() -> str: ...

# cards
def parse_card(text: str) -> int: ...
def card_to_str(card: int) -> str: ...

# evaluator
def evaluate(cards: list[int]) -> int: ...
def evaluate_batch(cards: NDArray[np.uint8]) -> NDArray[np.uint32]: ...
def hand_category(value: int) -> int: ...

# isomorphism
class HandIndexer:
    def __init__(self, cards_per_round: list[int]) -> None: ...
    @property
    def size(self) -> int: ...
    @property
    def total_cards(self) -> int: ...
    @property
    def cards_per_round(self) -> list[int]: ...
    def index(self, cards: list[int]) -> int: ...
    def unindex(self, index: int) -> list[int]: ...
    def index_batch(self, cards: NDArray[np.uint8]) -> NDArray[np.uint64]: ...
    def unindex_batch(self, indices: NDArray[np.uint64]) -> NDArray[np.uint8]: ...

# engine
class Street:
    PREFLOP: Street
    FLOP: Street
    TURN: Street
    RIVER: Street
    def __int__(self) -> int: ...
    @property
    def value(self) -> int: ...

class PlayerStatus:
    ACTIVE: PlayerStatus
    FOLDED: PlayerStatus
    ALL_IN: PlayerStatus
    def __int__(self) -> int: ...

class ActionType:
    FOLD: ActionType
    CHECK_CALL: ActionType
    BET_RAISE: ActionType

class Action:
    def __init__(self, type: ActionType, amount: int = 0) -> None: ...
    @property
    def type(self) -> ActionType: ...
    @property
    def amount(self) -> int: ...
    @staticmethod
    def fold() -> Action: ...
    @staticmethod
    def check_call() -> Action: ...
    @staticmethod
    def bet_raise_to(amount: int) -> Action: ...

class LegalActions:
    @property
    def fold(self) -> bool: ...
    @property
    def check_call(self) -> bool: ...
    @property
    def call_amount(self) -> int: ...
    @property
    def bet_raise(self) -> bool: ...
    @property
    def min_raise_to(self) -> int: ...
    @property
    def max_raise_to(self) -> int: ...

class Pot:
    @property
    def amount(self) -> int: ...
    @property
    def eligible(self) -> list[int]: ...

class HandState:
    def __init__(self, starting_stacks: list[int], small_blind: int, big_blind: int) -> None: ...
    @property
    def num_players(self) -> int: ...
    @property
    def button(self) -> int: ...
    @property
    def street(self) -> Street: ...
    @property
    def is_terminal(self) -> bool: ...
    @property
    def is_showdown(self) -> bool: ...
    @property
    def to_act(self) -> int: ...
    @property
    def current_bet(self) -> int: ...
    @property
    def pot(self) -> int: ...
    @property
    def non_folded(self) -> int: ...
    @property
    def stacks(self) -> list[int]: ...
    @property
    def bets(self) -> list[int]: ...
    @property
    def contributed(self) -> list[int]: ...
    @property
    def statuses(self) -> list[PlayerStatus]: ...
    @property
    def history(self) -> list[tuple[Street, int, Action]]: ...
    def legal_actions(self) -> LegalActions: ...
    def why_illegal(self, action: Action) -> str | None: ...
    def apply(self, action: Action) -> None: ...
    def pots(self) -> list[Pot]: ...
    def payoffs(self, hole_cards: list[list[int]], board: list[int]) -> list[int]: ...
    def copy(self) -> HandState: ...

# cfr
class NashConvResult:
    @property
    def best_response(self) -> list[float]: ...
    @property
    def on_policy(self) -> list[float]: ...
    @property
    def nash_conv(self) -> float: ...

class CfrSolver:
    def __init__(
        self,
        game: str,
        seed: int = 0,
        threads: int = 1,
        lcfr_until: int = 0,
        discount_interval: int = 1000,
        prune_after: int = -1,
        prune_probability: float = 0.95,
        prune_threshold: float = -1e9,
        regret_floor: float = -1e30,
        max_infosets: int = 1048576,
    ) -> None: ...
    def run(self, max_iterations: int, max_seconds: float = 1e18) -> int: ...
    @property
    def iteration(self) -> int: ...
    @property
    def num_infosets(self) -> int: ...
    @property
    def memory_bytes(self) -> int: ...
    @property
    def num_players(self) -> int: ...
    def nash_conv(self) -> NashConvResult: ...
    def average_strategy(self) -> list[tuple[int, list[float]]]: ...
    def save(self) -> bytes: ...
    def load(self, data: bytes) -> None: ...
